# Day Three: Transforming Data with Pandas

As always, import pandas using the conventional alias `pd` and set `max_columns` to None so that all columns are displayed.

In [2]:
import pandas as pd
pd.options.display.max_columns = None
print(pd.__version__)

2.3.3

## Processing JSON Files in Pandas: An Example API

First, let's look at the structure of an example JSON query result in both the browser and in Python. Today, we'll be focusing on statistics regarding the usage and expenditures of public libraries in Oregon.

This [Oregon Public Library Stastistics API](https://dev.socrata.com/foundry/data.oregon.gov/8zw7-zgjw) queries a database and retrieves all entries (that fit within a single JSON) that meet the selection requirements. The following query [https://data.oregon.gov/resource/8zw7-zgjw.json?year=2024](https://data.oregon.gov/resource/8zw7-zgjw.json?year=2024) returns information about public libraries in Oregon in the year 2024.

When opening the query in a browser like Firefox, you will notice that it looks like a **list** of **dictionaries**.

[{"libid":"OR0040","year":"2024","libraryname":"Adams Public Library","address":"PO Box 20","city":"Adams","zip":"97810","mailingaddress":"PO Box 20","mailingcity":"Adams","mailingzip":"97810","county":"Umatilla","phone":"541-566-3038","distcoop":"UCSLD","centrallibrary":"1","branches":"0","bookmobiles":"0","registeredusers":"237","registeredusersadded":"21","librariansalamls":"0","librarianstotal":"0.62","otherstaff":"0","volunteers":"0"...

### Reading JSONS

Pandas supports conversion of JSON files to DataFrames through the [**pd.read_json()**](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html) function. Parsing JSON files with nested structure will require more tuning of parameters, but the default arguments will work for this simple API.

In [20]:
URL = "https://data.oregon.gov/resource/8zw7-zgjw.json?year=2024"
libraries = pd.read_json(URL)
libraries.head(5) # Peek at the first five rows

,libid,year,libraryname,address,city,zip,mailingaddress,mailingcity,mailingzip,county,phone,distcoop,centrallibrary,branches,bookmobiles,registeredusers,registeredusersadded,librariansalamls,librarianstotal,otherstaff,volunteers,volunteerhours,friendsgroup,foundation,staffpositionsft,staffpositionsptunder20,staffpositionsptover20,staffpositionstemponcall,revenuecity,revenuecounty,revenuedistrict,revenuestate,revenuelsta,revenueotherfed,revenueotheroperating,captialrevenuelocal,capitalrevenuestate,capitalrevenuefed,capitalrevenueother,expendituressalarieswages,expendituresbenefits,expendituresprintmaterials,expenditureselectronicma,expendituresothermaterials,expendituresotheroperating,capitalexpendituresconst,capitalexpendituresequipment,capitalexpendituresother,collectionbooks,collectionbooksadded,collectionphysicalaudio,collectionphysicalaudioadded,collectionvideosphysical,collectionvideosphysicaladded,collectionothermaterials,collectionothermaterialsadded,collectionebooksodlc,collectionebooksodlcadded,collectionebookslocal,collectionebookslocaladded,collectionaudiobooksodlc,collectionaudiobooksodlcadded,collectionaudiobookslocal,collectionaudiobookslocaladded,collectiondigitalvideosodlc,collectiondigitalvideoso,collectiondigitalvideoslocal,collectiondigitalvideosl,collectionphysicalspanish,collectiondigitalspanish,collectiondatabaseslocal,collectiondatabaseslocaladded,collectionstatewidedatabases,collectionstatewidedatab,databaseusagestatewide,databaseusagelocal,circadult,circadultrenewals,circya,circyarenewals,circchildrens,circchildrensrenewals,circothermaterials,circothermaterialsrenewals,circnoagecategory,circnoagecategoryrenewals,circodlc,circecontentlocal,circnetworkloans,circillloans,circnetworkborrows,circillborrows,circnonresidents,referencetransactionsmethod,meetingroomuse,programssummerreading,programskids0_11,programskids0_11attendance,programskids0_5,programskids0_5attendance,programskids6_11,programskids6_11attendance,programsya12_18,programsya12_18attendance,programsadults,programsadultsattendance,programsgeneralinterest,programsgeneralinteresta,programsvirtual,programsvirtualattendance,programsrecorded,programsrecordedviews,programsselfdirected,programsselfdirectedpart,techpubliccomputerssessions,techpubliccomputersmethod,techpubliccomputers,techwifiscenario,techwifisessionsmethod,techdownloadspeed,techuploadspeed,techsharedils,techilsproductname,hoursweekday,hoursweekdayevening,hoursweekend,hoursweekendevening,weeksopenyear,hoursopenyear,libraryvisits,libraryvisitsmethod,facilitiessqftcentral,facilitiessqfttotal,facilitiesremodeldate,finesadultmaterials,fineschildrensmaterials,finesyamaterials,feesill,salarydirectorhourlylow,salarydirectorhourlyhigh,salarysupervisorylibhourlylow,salarysupervisorylibhourlyhigh,salarylibrarianhourlylow,salarylibrarianhourlyhigh,salarylibassisthourlylow,salarylibassisthourlyhigh,salarylibclerkhourlylow,salarylibclerkhourlyhigh,populationserved,interlibraryrelationshipcode,legalbasiscode,adminstructurecode,plscpublibdefinition,geographiccode,website,startdate,enddate,revenuelevy,capitalbond,circautorenewals,digitallitinstruction,techisptype,facilitiescapproject,techcircdevices,referencetransactions,techwifisessions,feesnonresident,expendituresservicecharges,collectionotherlanguages,revenuelevystartdate,revenuelevyenddate,capitalbondamount,capitalbondenddate
0,OR0040,2024,Adams Public Library,PO Box 20,Adams,97810,PO Box 20,Adams,97810,Umatilla,541-566-3038,UCSLD,1,0,0,237.0,21.0,0.00,0.62,0.00,0,0,False,False,0,0,1,1,0.0,0.0,49676.27,1000,7030,0.0,35036.0,0.0,0.0,0.0,0.0,31065.77,0.00,8672.86,0.00,0.00,11831.97,0.0,0.0,0.0,3155,330,85,38,714,97,23,7,62617,7261,511,119,40311,4260,388,1916,0,0,0,0,0,0,0,0,22,0,1,0,350.0,149.0,464.0,175.0,504.0,230.0,0.0,0.0,542.0,412.0,439.0,19,500,0,495,0,0.0,N/A (we do not track reference transactions),77.0,True,101,498,48.0,120.0,53.0,378.0,53.0,378.0,16.0,96.0,53.0,378,0,0,0,0,8.0,50.0,323.0,Actual count (we track each transaction as it ...,3,Wi-Fi extends outside building (left on 24/7),N/A (we don't track computer usage),373.4,269.20,Sage,Evergreen,25.0,0.0,0.0,0.0,52,1220.0,2740.0,Actual count (we track each visit as it happens),425,425,2003.0,FALSE,FALSE,FALSE,$0.00,19.80,19.80,0.00,0.00,0.00,0.00,13.20,13.20,0.00,0.00,1073,ME,CI,SO,True,PL2,{'url': 'http://www.cityofadamsoregon.com/adam...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,False,False,Fiber,No,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,OR0001,2024,Agness Community Library District,PO BOX 33,AGNESS,97406,PO Box 33,Agness,97406,Curry,541-247-6323,NONE,1,0,0,81.0,0.0,0.00,0.35,0.25,16,90,False,False,0,1,0,1,0.0,0.0,24732.13,1000,0,0.0,0.0,0.0,0.0,0.0,0.0,12012.00,3253.00,0.00,0.00,0.00,10500.00,0.0,0.0,0.0,7339,20,47,47,770,10,0,0,62617,7261,0,0,40311,4260,0,0,0,0,0,0,3,0,0,0,22,0,3,0,600.0,211.0,30.0,30.0,85.0,16.0,0.0,0.0,0.0,0.0,16.0,0,370,0,1289,3,0.0,Actual count (we track each transaction as it ...,0.0,True,79,60,7.0,30.0,72.0,30.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,262.0,Actual count (we track each transaction as it ...,2,Wi-Fi extends outside building (left on 24/7),Actual count (we track each transaction as it ...,4.14,0.34,Coastline,Koha,14.0,0.0,0.0,0.0,52,670.0,653.0,Actual count (we track each visit as it happens),865,865,NaN,FALSE,FALSE,FALSE,$2.00,NaN,18.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15.00,156,ME,LD,SO,True,OTH,{'url': 'https://agnesscommunitylibrary.weebly...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,True,Satellite,No,False,1955.0,614.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN
2,OR0106,2024,Albany Public Library,2450 14th Ave SE,Albany,97322,2450 14th Ave SE,Albany,97322,Linn,541-917-7581,NONE,1,1,0,39594.0,3680.0,9.65,9.65,10.40,299,3540,True,True,14,0,8,0,3292461.0,0.0,0.00,9127,0,0.0,250817.0,0.0,0.0,0.0,0.0,1387482.84,1011784.22,133797.77,44796.22,29286.38,1063254.00,0.0,0.0,0.0,136615,8024,7597,282,13418,632,1210,337,62617,7261,1940,446,40311,4260,794,220,0,0,0,0,4549,1460,9,0,22,0,471,23138,113169.0,66231.0,22652.0,15203.0,115301.0,75878.0,0.0,0.0,0.0,0.0,47487.0,10879,0,588,0,130,19275.0,Estimate (we use a sampling method),596.0,True,369,10604,287.0,7406.0,82.0,3198.0,76.0,849.0,46.0,1384.0,0.0,0,0,0,0,0,NaN,NaN,13238.0,Actual count (we track each transaction as it ...,31,Wi-Fi extends outside building (left on throug...,N/A (we don't track computer usage),"1,000.00",1000.00,Linn Libraries Consortium,Evergreen,39.0,8.0,10.0,0.0,52,2908.0,117398.0,Actual count (we track each visit as it happens),49170,49170,2009.0,FALSE,FALSE,FALSE,$3.00,56.88,76.79,36.22,48.90,27.56,38.72,21.06,26.87,17.16,21.81,57997,NO,CI,MO,True,PL1,{'url': 'http://www.library.cityofalbany.net'},2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,False,Fiber,No,True,8723.0,NaN,80.0,Administration; Facilities; Human Resources; I...,NaN,NaN,NaN,NaN,NaN
3,OR9010,2024,Aloha Community Library,17455 SW Farmington Rd. Ste. 26A,Aloha,97007,17455 SW Farmington Rd. Ste. 26A,Aloha,97007,Washington,503-259-0185,WCCLS,1,0,0,9687.0,1339.0,3.00,3.00,5.90,22,1059,False,False,5,10,2,0,0.0,568383.0,0.00,3650,0,0.0,105589.0,0.0,0.0,0.0,0.0,392677.00,74261.00,20515.00,0.00,7235.00,197371.00,0.0,4543.0,2807.0,25453,2339,510,39,4568,379,150,49,0,0,225921,55100,0,0,196400,30239,0,0,33218,2681,1428,17891,15,0,22,0,164,10006,43228.0,37230.0,3955.0,4951.0,39583.0,42646.0,787.0,686.0,17.0,16.0,0.0,74441,43607,273,142884,446,1829.0,Actual count (we track each transaction as it ...,6.0,True,110,2440,86.0,1606.0,24.0,834.0,3.0,17.0,93.0,392.0,4.0,235,11,40,0,0,19.0,929.0,4827.0,Actual count (we track each transaction as it ...,9,Wi-Fi extends outside building (left on throug...,Actual count (we track each transaction as it ...,100,100.00,WCCLS,Polaris,35.0,5.0,5.0,0.0,52,2268.0,52962.0,Actual count (we track each visit as it happens),9350,9350,2023.0,FALSE,FALSE,FALSE,$0.00,31.41,31.41,26.60,31.42,22.71,22.71,17.10,19.05,15.60,15.60,21649,ME,NP,SO,True,PL2,{'url': 'https://alohalibrary.org/'},2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,True,False,True,True,Fiber,No,False,1188.0,6871.0,140.0,NaN,Japanese; Korean; Russian; Vietnamese; other,2020.0,2026.0,NaN,NaN
4,OR0002,2024,Amity Public Library,P.O. Box 470,Amity,97101,PO Box 470,Amity,97101,Yamhill,503-835-8181,CCRLS,1,0,0,695.0,94.0,0.00,0.00,0.50,5,73,True,False,0,3,0,0,918.0,0.0,8103.00,1000,0,0.0,96.0,0.0,0.0,0.0,0.0,18260.00,1534.00,450.02,0.00,342.62,300.00,0.0,0.0,0.0,12025,281,158,7,980,6,15,5,62617,7261,0,0,40311,4260,0,0,0,0,0,0,28,0,0,0,22,0,0,0,3743.0,3042.0,198.0,146.0,1107.0,740.0,29.0,51.0,0.0,0.0,2018.0,0,2508,147,2508,0,3495.0,Estimate (we use a sampling method),1.0,True,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,244,0,0,0,0,11.0,50.0,328.0,Actual count (we track each transaction as it ...,4,Wi-Fi only available inside during open hours,Estimate (using a sampling method),14,13.60,CCRLS,Sirsi/Dynix,16.0,0.0,4.0,0.0,52,1040.0,2646.0,Actual count (we track each visit as it happens),960,960,NaN,TRUE,TRUE,TRUE,$0.00,15.25,15.25,14.25,14.25,14.25,14.25,NaN,NaN,NaN,NaN,3663,ME,CI,SO,True,PL1,{'url': 'https://www.cityofamityoregon.org/lib...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,False,Fiber,No,True,8.0,5.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN

Let's use `.info()` to get a little more information about this DataFrame.

In [33]:
libraries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Columns: 173 entries, libid to capitalbondenddate
dtypes: bool(9), float64(73), int64(59), object(32)
memory usage: 175.6+ KB

This dataset has more columns than Pandas will automatically summarize for you.
However, this dataset is fully documented on its homepage on the [Oregon Data Portal](https://data.oregon.gov/dataset/Oregon-Public-Library-Statistics/8zw7-zgjw/about_data).

## Inferring Columns in DataFrames

Sometimes we want to change values in DataFrames in a systematic way. Let's start with creation new columns as a function of **other columns**.

Operations on Series are vectorized. That means they are applied to each individual entry in the Series in parallel. Let's look at the numeric column `"appeared`", which is the date the programming language was introduced to the public.

In [46]:
pldb["appeared"]

id
javascript      1995
c               1972
python          1991
java            1995
cpp             1985
                ...
dat-protocol    2013
mariadb         2009
io              2002
sourcepawn      2014
qalb            2012
Name: appeared, Length: 500, dtype: int64

One way to manipulate a **Series** is to add a scalar constant.

In [47]:
pldb["appeared"] + 2000 # This is shorthand for adding 20 to each value in the Series

id
javascript      3995
c               3972
python          3991
java            3995
cpp             3985
                ...
dat-protocol    4013
mariadb         4009
io              4002
sourcepawn      4014
qalb            4012
Name: appeared, Length: 500, dtype: int64

Multiplication by a scalar is also simple and vectorized.

In [48]:
pldb["appeared"] * 0.5 # Multiply each value by 0.5

id
javascript       997.5
c                986.0
python           995.5
java             997.5
cpp              992.5
                 ...
dat-protocol    1006.5
mariadb         1004.5
io              1001.0
sourcepawn      1007.0
qalb            1006.0
Name: appeared, Length: 500, dtype: float64

Unlike *aggregation* functions, vectorized operations return a Series or DataFrame of the same size.

In [51]:
pldb["appeared"].max() # This will return one value, it aggregates

2024

### Refresher: Python String Functions

Pandas has special string-processing functions for Series and DataFrames inspired by Python's built-in [string operations](https://docs.python.org/3/library/stdtypes.html#string-methods) methods.

Let's review a few string methods: `str.lower()`, `str.isnumeric()`, `str.replace()`.

`str.lower()` returns a lowercase version of the string.

In [19]:
shouting = "ALL CAPS"
shouting.lower()

'all caps'

`str.isnumeric()` tests whether or not a string is a number. Any alphabetic characters will cause this to return `False`.

In [20]:
shouting.isnumeric()

False

In [21]:
lucky = "12"
lucky.isnumeric()

True

`str.replace(old, new)` returns a copy of a string with all occurrences of substring `old` replaced by `new`.

A *substring* is 1 or more consecutive characters inside an existing string.
`"BAG"` is a substring of `"BAGEL"` but `"NEW YORK"` is not.

In [22]:
less_shouting = str.replace(shouting, "ALL", "some")
less_shouting

'some CAPS'

The `str.replace()` function is especially convenient for removing unwanted characters.

In [24]:
has_spaces = "This has spaces"
has_spaces.replace(" ", "_") # Replaces spaces with _

'This_has_spaces'

## String Manipulation in DataFrames

We can apply these methods on *any* Series of strings, not just column or row names.

String functions allow us to clean and normalize categorical columns in DataFrame
by applying the same operation to each item. Let's look at the first
5 rows of `libraries` with `head` to see if there are any inconsistencies.

In [22]:
libraries.head(5)

,libid,year,libraryname,address,city,zip,mailingaddress,mailingcity,mailingzip,county,phone,distcoop,centrallibrary,branches,bookmobiles,registeredusers,registeredusersadded,librariansalamls,librarianstotal,otherstaff,volunteers,volunteerhours,friendsgroup,foundation,staffpositionsft,staffpositionsptunder20,staffpositionsptover20,staffpositionstemponcall,revenuecity,revenuecounty,revenuedistrict,revenuestate,revenuelsta,revenueotherfed,revenueotheroperating,captialrevenuelocal,capitalrevenuestate,capitalrevenuefed,capitalrevenueother,expendituressalarieswages,expendituresbenefits,expendituresprintmaterials,expenditureselectronicma,expendituresothermaterials,expendituresotheroperating,capitalexpendituresconst,capitalexpendituresequipment,capitalexpendituresother,collectionbooks,collectionbooksadded,collectionphysicalaudio,collectionphysicalaudioadded,collectionvideosphysical,collectionvideosphysicaladded,collectionothermaterials,collectionothermaterialsadded,collectionebooksodlc,collectionebooksodlcadded,collectionebookslocal,collectionebookslocaladded,collectionaudiobooksodlc,collectionaudiobooksodlcadded,collectionaudiobookslocal,collectionaudiobookslocaladded,collectiondigitalvideosodlc,collectiondigitalvideoso,collectiondigitalvideoslocal,collectiondigitalvideosl,collectionphysicalspanish,collectiondigitalspanish,collectiondatabaseslocal,collectiondatabaseslocaladded,collectionstatewidedatabases,collectionstatewidedatab,databaseusagestatewide,databaseusagelocal,circadult,circadultrenewals,circya,circyarenewals,circchildrens,circchildrensrenewals,circothermaterials,circothermaterialsrenewals,circnoagecategory,circnoagecategoryrenewals,circodlc,circecontentlocal,circnetworkloans,circillloans,circnetworkborrows,circillborrows,circnonresidents,referencetransactionsmethod,meetingroomuse,programssummerreading,programskids0_11,programskids0_11attendance,programskids0_5,programskids0_5attendance,programskids6_11,programskids6_11attendance,programsya12_18,programsya12_18attendance,programsadults,programsadultsattendance,programsgeneralinterest,programsgeneralinteresta,programsvirtual,programsvirtualattendance,programsrecorded,programsrecordedviews,programsselfdirected,programsselfdirectedpart,techpubliccomputerssessions,techpubliccomputersmethod,techpubliccomputers,techwifiscenario,techwifisessionsmethod,techdownloadspeed,techuploadspeed,techsharedils,techilsproductname,hoursweekday,hoursweekdayevening,hoursweekend,hoursweekendevening,weeksopenyear,hoursopenyear,libraryvisits,libraryvisitsmethod,facilitiessqftcentral,facilitiessqfttotal,facilitiesremodeldate,finesadultmaterials,fineschildrensmaterials,finesyamaterials,feesill,salarydirectorhourlylow,salarydirectorhourlyhigh,salarysupervisorylibhourlylow,salarysupervisorylibhourlyhigh,salarylibrarianhourlylow,salarylibrarianhourlyhigh,salarylibassisthourlylow,salarylibassisthourlyhigh,salarylibclerkhourlylow,salarylibclerkhourlyhigh,populationserved,interlibraryrelationshipcode,legalbasiscode,adminstructurecode,plscpublibdefinition,geographiccode,website,startdate,enddate,revenuelevy,capitalbond,circautorenewals,digitallitinstruction,techisptype,facilitiescapproject,techcircdevices,referencetransactions,techwifisessions,feesnonresident,expendituresservicecharges,collectionotherlanguages,revenuelevystartdate,revenuelevyenddate,capitalbondamount,capitalbondenddate
0,OR0040,2024,Adams Public Library,PO Box 20,Adams,97810,PO Box 20,Adams,97810,Umatilla,541-566-3038,UCSLD,1,0,0,237.0,21.0,0.00,0.62,0.00,0,0,False,False,0,0,1,1,0.0,0.0,49676.27,1000,7030,0.0,35036.0,0.0,0.0,0.0,0.0,31065.77,0.00,8672.86,0.00,0.00,11831.97,0.0,0.0,0.0,3155,330,85,38,714,97,23,7,62617,7261,511,119,40311,4260,388,1916,0,0,0,0,0,0,0,0,22,0,1,0,350.0,149.0,464.0,175.0,504.0,230.0,0.0,0.0,542.0,412.0,439.0,19,500,0,495,0,0.0,N/A (we do not track reference transactions),77.0,True,101,498,48.0,120.0,53.0,378.0,53.0,378.0,16.0,96.0,53.0,378,0,0,0,0,8.0,50.0,323.0,Actual count (we track each transaction as it ...,3,Wi-Fi extends outside building (left on 24/7),N/A (we don't track computer usage),373.4,269.20,Sage,Evergreen,25.0,0.0,0.0,0.0,52,1220.0,2740.0,Actual count (we track each visit as it happens),425,425,2003.0,FALSE,FALSE,FALSE,$0.00,19.80,19.80,0.00,0.00,0.00,0.00,13.20,13.20,0.00,0.00,1073,ME,CI,SO,True,PL2,{'url': 'http://www.cityofadamsoregon.com/adam...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,False,False,Fiber,No,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,OR0001,2024,Agness Community Library District,PO BOX 33,AGNESS,97406,PO Box 33,Agness,97406,Curry,541-247-6323,NONE,1,0,0,81.0,0.0,0.00,0.35,0.25,16,90,False,False,0,1,0,1,0.0,0.0,24732.13,1000,0,0.0,0.0,0.0,0.0,0.0,0.0,12012.00,3253.00,0.00,0.00,0.00,10500.00,0.0,0.0,0.0,7339,20,47,47,770,10,0,0,62617,7261,0,0,40311,4260,0,0,0,0,0,0,3,0,0,0,22,0,3,0,600.0,211.0,30.0,30.0,85.0,16.0,0.0,0.0,0.0,0.0,16.0,0,370,0,1289,3,0.0,Actual count (we track each transaction as it ...,0.0,True,79,60,7.0,30.0,72.0,30.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,262.0,Actual count (we track each transaction as it ...,2,Wi-Fi extends outside building (left on 24/7),Actual count (we track each transaction as it ...,4.14,0.34,Coastline,Koha,14.0,0.0,0.0,0.0,52,670.0,653.0,Actual count (we track each visit as it happens),865,865,NaN,FALSE,FALSE,FALSE,$2.00,NaN,18.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,15.00,156,ME,LD,SO,True,OTH,{'url': 'https://agnesscommunitylibrary.weebly...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,True,Satellite,No,False,1955.0,614.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN
2,OR0106,2024,Albany Public Library,2450 14th Ave SE,Albany,97322,2450 14th Ave SE,Albany,97322,Linn,541-917-7581,NONE,1,1,0,39594.0,3680.0,9.65,9.65,10.40,299,3540,True,True,14,0,8,0,3292461.0,0.0,0.00,9127,0,0.0,250817.0,0.0,0.0,0.0,0.0,1387482.84,1011784.22,133797.77,44796.22,29286.38,1063254.00,0.0,0.0,0.0,136615,8024,7597,282,13418,632,1210,337,62617,7261,1940,446,40311,4260,794,220,0,0,0,0,4549,1460,9,0,22,0,471,23138,113169.0,66231.0,22652.0,15203.0,115301.0,75878.0,0.0,0.0,0.0,0.0,47487.0,10879,0,588,0,130,19275.0,Estimate (we use a sampling method),596.0,True,369,10604,287.0,7406.0,82.0,3198.0,76.0,849.0,46.0,1384.0,0.0,0,0,0,0,0,NaN,NaN,13238.0,Actual count (we track each transaction as it ...,31,Wi-Fi extends outside building (left on throug...,N/A (we don't track computer usage),"1,000.00",1000.00,Linn Libraries Consortium,Evergreen,39.0,8.0,10.0,0.0,52,2908.0,117398.0,Actual count (we track each visit as it happens),49170,49170,2009.0,FALSE,FALSE,FALSE,$3.00,56.88,76.79,36.22,48.90,27.56,38.72,21.06,26.87,17.16,21.81,57997,NO,CI,MO,True,PL1,{'url': 'http://www.library.cityofalbany.net'},2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,False,Fiber,No,True,8723.0,NaN,80.0,Administration; Facilities; Human Resources; I...,NaN,NaN,NaN,NaN,NaN
3,OR9010,2024,Aloha Community Library,17455 SW Farmington Rd. Ste. 26A,Aloha,97007,17455 SW Farmington Rd. Ste. 26A,Aloha,97007,Washington,503-259-0185,WCCLS,1,0,0,9687.0,1339.0,3.00,3.00,5.90,22,1059,False,False,5,10,2,0,0.0,568383.0,0.00,3650,0,0.0,105589.0,0.0,0.0,0.0,0.0,392677.00,74261.00,20515.00,0.00,7235.00,197371.00,0.0,4543.0,2807.0,25453,2339,510,39,4568,379,150,49,0,0,225921,55100,0,0,196400,30239,0,0,33218,2681,1428,17891,15,0,22,0,164,10006,43228.0,37230.0,3955.0,4951.0,39583.0,42646.0,787.0,686.0,17.0,16.0,0.0,74441,43607,273,142884,446,1829.0,Actual count (we track each transaction as it ...,6.0,True,110,2440,86.0,1606.0,24.0,834.0,3.0,17.0,93.0,392.0,4.0,235,11,40,0,0,19.0,929.0,4827.0,Actual count (we track each transaction as it ...,9,Wi-Fi extends outside building (left on throug...,Actual count (we track each transaction as it ...,100,100.00,WCCLS,Polaris,35.0,5.0,5.0,0.0,52,2268.0,52962.0,Actual count (we track each visit as it happens),9350,9350,2023.0,FALSE,FALSE,FALSE,$0.00,31.41,31.41,26.60,31.42,22.71,22.71,17.10,19.05,15.60,15.60,21649,ME,NP,SO,True,PL2,{'url': 'https://alohalibrary.org/'},2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,True,False,True,True,Fiber,No,False,1188.0,6871.0,140.0,NaN,Japanese; Korean; Russian; Vietnamese; other,2020.0,2026.0,NaN,NaN
4,OR0002,2024,Amity Public Library,P.O. Box 470,Amity,97101,PO Box 470,Amity,97101,Yamhill,503-835-8181,CCRLS,1,0,0,695.0,94.0,0.00,0.00,0.50,5,73,True,False,0,3,0,0,918.0,0.0,8103.00,1000,0,0.0,96.0,0.0,0.0,0.0,0.0,18260.00,1534.00,450.02,0.00,342.62,300.00,0.0,0.0,0.0,12025,281,158,7,980,6,15,5,62617,7261,0,0,40311,4260,0,0,0,0,0,0,28,0,0,0,22,0,0,0,3743.0,3042.0,198.0,146.0,1107.0,740.0,29.0,51.0,0.0,0.0,2018.0,0,2508,147,2508,0,3495.0,Estimate (we use a sampling method),1.0,True,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,244,0,0,0,0,11.0,50.0,328.0,Actual count (we track each transaction as it ...,4,Wi-Fi only available inside during open hours,Estimate (using a sampling method),14,13.60,CCRLS,Sirsi/Dynix,16.0,0.0,4.0,0.0,52,1040.0,2646.0,Actual count (we track each visit as it happens),960,960,NaN,TRUE,TRUE,TRUE,$0.00,15.25,15.25,14.25,14.25,14.25,14.25,NaN,NaN,NaN,NaN,3663,ME,CI,SO,True,PL1,{'url': 'https://www.cityofamityoregon.org/lib...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,False,Fiber,No,True,8.0,5.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN

In the `city` column, I see inconsistent capitalization. We could fix this with `.str.title()`, which capitalizes the first letter of each string and lowers the rest.

In [23]:
libraries["city"].str.title()

0            Adams
1           Agness
2           Albany
3            Aloha
4            Amity
          ...
131    Wilsonville
132        Winston
133       Woodburn
134        Yachats
135       Yoncalla
Name: city, Length: 136, dtype: object

Great! But, don't forget, DataFrame operations return *copies*, so there is no change to the
original `libraries` DataFrame unless I replace the existing `city` column.

In [25]:
libraries["city"] = libraries["city"].str.title() # Assign back

In [26]:
libraries.head(3)

,libid,year,libraryname,address,city,zip,mailingaddress,mailingcity,mailingzip,county,phone,distcoop,centrallibrary,branches,bookmobiles,registeredusers,registeredusersadded,librariansalamls,librarianstotal,otherstaff,volunteers,volunteerhours,friendsgroup,foundation,staffpositionsft,staffpositionsptunder20,staffpositionsptover20,staffpositionstemponcall,revenuecity,revenuecounty,revenuedistrict,revenuestate,revenuelsta,revenueotherfed,revenueotheroperating,captialrevenuelocal,capitalrevenuestate,capitalrevenuefed,capitalrevenueother,expendituressalarieswages,expendituresbenefits,expendituresprintmaterials,expenditureselectronicma,expendituresothermaterials,expendituresotheroperating,capitalexpendituresconst,capitalexpendituresequipment,capitalexpendituresother,collectionbooks,collectionbooksadded,collectionphysicalaudio,collectionphysicalaudioadded,collectionvideosphysical,collectionvideosphysicaladded,collectionothermaterials,collectionothermaterialsadded,collectionebooksodlc,collectionebooksodlcadded,collectionebookslocal,collectionebookslocaladded,collectionaudiobooksodlc,collectionaudiobooksodlcadded,collectionaudiobookslocal,collectionaudiobookslocaladded,collectiondigitalvideosodlc,collectiondigitalvideoso,collectiondigitalvideoslocal,collectiondigitalvideosl,collectionphysicalspanish,collectiondigitalspanish,collectiondatabaseslocal,collectiondatabaseslocaladded,collectionstatewidedatabases,collectionstatewidedatab,databaseusagestatewide,databaseusagelocal,circadult,circadultrenewals,circya,circyarenewals,circchildrens,circchildrensrenewals,circothermaterials,circothermaterialsrenewals,circnoagecategory,circnoagecategoryrenewals,circodlc,circecontentlocal,circnetworkloans,circillloans,circnetworkborrows,circillborrows,circnonresidents,referencetransactionsmethod,meetingroomuse,programssummerreading,programskids0_11,programskids0_11attendance,programskids0_5,programskids0_5attendance,programskids6_11,programskids6_11attendance,programsya12_18,programsya12_18attendance,programsadults,programsadultsattendance,programsgeneralinterest,programsgeneralinteresta,programsvirtual,programsvirtualattendance,programsrecorded,programsrecordedviews,programsselfdirected,programsselfdirectedpart,techpubliccomputerssessions,techpubliccomputersmethod,techpubliccomputers,techwifiscenario,techwifisessionsmethod,techdownloadspeed,techuploadspeed,techsharedils,techilsproductname,hoursweekday,hoursweekdayevening,hoursweekend,hoursweekendevening,weeksopenyear,hoursopenyear,libraryvisits,libraryvisitsmethod,facilitiessqftcentral,facilitiessqfttotal,facilitiesremodeldate,finesadultmaterials,fineschildrensmaterials,finesyamaterials,feesill,salarydirectorhourlylow,salarydirectorhourlyhigh,salarysupervisorylibhourlylow,salarysupervisorylibhourlyhigh,salarylibrarianhourlylow,salarylibrarianhourlyhigh,salarylibassisthourlylow,salarylibassisthourlyhigh,salarylibclerkhourlylow,salarylibclerkhourlyhigh,populationserved,interlibraryrelationshipcode,legalbasiscode,adminstructurecode,plscpublibdefinition,geographiccode,website,startdate,enddate,revenuelevy,capitalbond,circautorenewals,digitallitinstruction,techisptype,facilitiescapproject,techcircdevices,referencetransactions,techwifisessions,feesnonresident,expendituresservicecharges,collectionotherlanguages,revenuelevystartdate,revenuelevyenddate,capitalbondamount,capitalbondenddate
0,OR0040,2024,Adams Public Library,PO Box 20,Adams,97810,PO Box 20,Adams,97810,Umatilla,541-566-3038,UCSLD,1,0,0,237.0,21.0,0.00,0.62,0.00,0,0,False,False,0,0,1,1,0.0,0.0,49676.27,1000,7030,0.0,35036.0,0.0,0.0,0.0,0.0,31065.77,0.00,8672.86,0.00,0.00,11831.97,0.0,0.0,0.0,3155,330,85,38,714,97,23,7,62617,7261,511,119,40311,4260,388,1916,0,0,0,0,0,0,0,0,22,0,1,0,350.0,149.0,464.0,175.0,504.0,230.0,0.0,0.0,542.0,412.0,439.0,19,500,0,495,0,0.0,N/A (we do not track reference transactions),77.0,True,101,498,48.0,120.0,53.0,378.0,53.0,378.0,16.0,96.0,53.0,378,0,0,0,0,8.0,50.0,323.0,Actual count (we track each transaction as it ...,3,Wi-Fi extends outside building (left on 24/7),N/A (we don't track computer usage),373.4,269.20,Sage,Evergreen,25.0,0.0,0.0,0.0,52,1220.0,2740.0,Actual count (we track each visit as it happens),425,425,2003.0,FALSE,FALSE,FALSE,$0.00,19.80,19.80,0.00,0.0,0.00,0.00,13.20,13.20,0.00,0.00,1073,ME,CI,SO,True,PL2,{'url': 'http://www.cityofadamsoregon.com/adam...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,False,False,Fiber,No,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,OR0001,2024,Agness Community Library District,PO BOX 33,Agness,97406,PO Box 33,Agness,97406,Curry,541-247-6323,NONE,1,0,0,81.0,0.0,0.00,0.35,0.25,16,90,False,False,0,1,0,1,0.0,0.0,24732.13,1000,0,0.0,0.0,0.0,0.0,0.0,0.0,12012.00,3253.00,0.00,0.00,0.00,10500.00,0.0,0.0,0.0,7339,20,47,47,770,10,0,0,62617,7261,0,0,40311,4260,0,0,0,0,0,0,3,0,0,0,22,0,3,0,600.0,211.0,30.0,30.0,85.0,16.0,0.0,0.0,0.0,0.0,16.0,0,370,0,1289,3,0.0,Actual count (we track each transaction as it ...,0.0,True,79,60,7.0,30.0,72.0,30.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,262.0,Actual count (we track each transaction as it ...,2,Wi-Fi extends outside building (left on 24/7),Actual count (we track each transaction as it ...,4.14,0.34,Coastline,Koha,14.0,0.0,0.0,0.0,52,670.0,653.0,Actual count (we track each visit as it happens),865,865,NaN,FALSE,FALSE,FALSE,$2.00,NaN,18.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,15.00,156,ME,LD,SO,True,OTH,{'url': 'https://agnesscommunitylibrary.weebly...,2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,True,Satellite,No,False,1955.0,614.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN
2,OR0106,2024,Albany Public Library,2450 14th Ave SE,Albany,97322,2450 14th Ave SE,Albany,97322,Linn,541-917-7581,NONE,1,1,0,39594.0,3680.0,9.65,9.65,10.40,299,3540,True,True,14,0,8,0,3292461.0,0.0,0.00,9127,0,0.0,250817.0,0.0,0.0,0.0,0.0,1387482.84,1011784.22,133797.77,44796.22,29286.38,1063254.00,0.0,0.0,0.0,136615,8024,7597,282,13418,632,1210,337,62617,7261,1940,446,40311,4260,794,220,0,0,0,0,4549,1460,9,0,22,0,471,23138,113169.0,66231.0,22652.0,15203.0,115301.0,75878.0,0.0,0.0,0.0,0.0,47487.0,10879,0,588,0,130,19275.0,Estimate (we use a sampling method),596.0,True,369,10604,287.0,7406.0,82.0,3198.0,76.0,849.0,46.0,1384.0,0.0,0,0,0,0,0,NaN,NaN,13238.0,Actual count (we track each transaction as it ...,31,Wi-Fi extends outside building (left on throug...,N/A (we don't track computer usage),"1,000.00",1000.00,Linn Libraries Consortium,Evergreen,39.0,8.0,10.0,0.0,52,2908.0,117398.0,Actual count (we track each visit as it happens),49170,49170,2009.0,FALSE,FALSE,FALSE,$3.00,56.88,76.79,36.22,48.9,27.56,38.72,21.06,26.87,17.16,21.81,57997,NO,CI,MO,True,PL1,{'url': 'http://www.library.cityofalbany.net'},2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,False,True,False,Fiber,No,True,8723.0,NaN,80.0,Administration; Facilities; Human Resources; I...,NaN,NaN,NaN,NaN,NaN

These string methods will *not* work on rows or columns with numeric values. We will get an **AttributeError** by applying them to columns of the wrong type.

In [29]:
libraries["mailingzip"].str.lower()

AttributeError: Can only use .str accessor with string values!

### An Example Cleaning Task: Standardizing Phone Numbers

Not every string function returns another string! For example, let's say we want
to validate the formatting of the `phone` column.

We can use `.str.len()` to return the length in characters of each phone number.

In [35]:
libraries["phone"].str.len()

0      12
1      12
2      12
3      12
4      12
       ..
131    12
132    12
133    12
134    12
135    12
Name: phone, Length: 136, dtype: int64

Let's assume a correctly formatted phone number is ten digits divided into three groups separated by hyphens. We assume a length of 12 character is correct. By applying the `.value_counts()` method, we see that there are two phone numbers with invalid formatting.

In [39]:
phone_lengths = libraries["phone"].str.len()
phone_lengths.value_counts()

phone
12    134
17      1
18      1
Name: count, dtype: int64

Let's inspect these rows in the original DataFrame. Because `libraries` and `phone_lengths` have same indices, we can use boolean indexing to slice the `libraries` DataFrame to rows
where phone_lengths (a one-dimensional Series) is > 12.

In [41]:
libraries[phone_lengths > 12]

,libid,year,libraryname,address,city,zip,mailingaddress,mailingcity,mailingzip,county,phone,distcoop,centrallibrary,branches,bookmobiles,registeredusers,registeredusersadded,librariansalamls,librarianstotal,otherstaff,volunteers,volunteerhours,friendsgroup,foundation,staffpositionsft,staffpositionsptunder20,staffpositionsptover20,staffpositionstemponcall,revenuecity,revenuecounty,revenuedistrict,revenuestate,revenuelsta,revenueotherfed,revenueotheroperating,captialrevenuelocal,capitalrevenuestate,capitalrevenuefed,capitalrevenueother,expendituressalarieswages,expendituresbenefits,expendituresprintmaterials,expenditureselectronicma,expendituresothermaterials,expendituresotheroperating,capitalexpendituresconst,capitalexpendituresequipment,capitalexpendituresother,collectionbooks,collectionbooksadded,collectionphysicalaudio,collectionphysicalaudioadded,collectionvideosphysical,collectionvideosphysicaladded,collectionothermaterials,collectionothermaterialsadded,collectionebooksodlc,collectionebooksodlcadded,collectionebookslocal,collectionebookslocaladded,collectionaudiobooksodlc,collectionaudiobooksodlcadded,collectionaudiobookslocal,collectionaudiobookslocaladded,collectiondigitalvideosodlc,collectiondigitalvideoso,collectiondigitalvideoslocal,collectiondigitalvideosl,collectionphysicalspanish,collectiondigitalspanish,collectiondatabaseslocal,collectiondatabaseslocaladded,collectionstatewidedatabases,collectionstatewidedatab,databaseusagestatewide,databaseusagelocal,circadult,circadultrenewals,circya,circyarenewals,circchildrens,circchildrensrenewals,circothermaterials,circothermaterialsrenewals,circnoagecategory,circnoagecategoryrenewals,circodlc,circecontentlocal,circnetworkloans,circillloans,circnetworkborrows,circillborrows,circnonresidents,referencetransactionsmethod,meetingroomuse,programssummerreading,programskids0_11,programskids0_11attendance,programskids0_5,programskids0_5attendance,programskids6_11,programskids6_11attendance,programsya12_18,programsya12_18attendance,programsadults,programsadultsattendance,programsgeneralinterest,programsgeneralinteresta,programsvirtual,programsvirtualattendance,programsrecorded,programsrecordedviews,programsselfdirected,programsselfdirectedpart,techpubliccomputerssessions,techpubliccomputersmethod,techpubliccomputers,techwifiscenario,techwifisessionsmethod,techdownloadspeed,techuploadspeed,techsharedils,techilsproductname,hoursweekday,hoursweekdayevening,hoursweekend,hoursweekendevening,weeksopenyear,hoursopenyear,libraryvisits,libraryvisitsmethod,facilitiessqftcentral,facilitiessqfttotal,facilitiesremodeldate,finesadultmaterials,fineschildrensmaterials,finesyamaterials,feesill,salarydirectorhourlylow,salarydirectorhourlyhigh,salarysupervisorylibhourlylow,salarysupervisorylibhourlyhigh,salarylibrarianhourlylow,salarylibrarianhourlyhigh,salarylibassisthourlylow,salarylibassisthourlyhigh,salarylibclerkhourlylow,salarylibclerkhourlyhigh,populationserved,interlibraryrelationshipcode,legalbasiscode,adminstructurecode,plscpublibdefinition,geographiccode,website,startdate,enddate,revenuelevy,capitalbond,circautorenewals,digitallitinstruction,techisptype,facilitiescapproject,techcircdevices,referencetransactions,techwifisessions,feesnonresident,expendituresservicecharges,collectionotherlanguages,revenuelevystartdate,revenuelevyenddate,capitalbondamount,capitalbondenddate
85,OR0141,2024,North Plains Public Library,31360 NW Commercial St.,North Plains,97133,31360 NW Commercial St.,North Plains,97133,Washington,503-647-5051 x102,WCCLS,1,0,0,2501.0,274.0,1.9,1.9,4.00,69,3010,True,False,4,0,1,7,421954.0,203472.0,0.0,1054,0,14492.0,60863.0,0.0,0.0,0.0,0.0,383665.0,162581.0,36725.0,0.0,4937.0,78519.0,0.0,26450.0,0.0,16226,2244,296,29,2342,139,99,9,0,0,248195,143328,0,0,188646,130399,0,0,33218,2681,279,17891,15,0,22,0,36,2224,15232.0,11786.0,1366.0,1537.0,18414.0,17244.0,390.0,399.0,103.0,125.0,0.0,22035,70649,328,51468,98,583.0,Estimate (we use a sampling method),0.0,True,135,2532,44.0,825.0,91.0,1707.0,24.0,313.0,38.0,278.0,9.0,770,17,217,0,0,84.0,879.0,1662.0,Actual count (we track each transaction as it ...,6,Wi-Fi extends outside building (left on 24/7),Actual count (we track each transaction as it ...,100,100.0,WCCLS,Polaris,35.0,10.0,7.0,0.0,52,2704.0,32747.0,Actual count (we track each visit as it happens),2500,2500,NaN,FALSE,FALSE,FALSE,$0.00,50.77,64.59,0.00,0.00,29.68,37.76,19.04,28.51,0.00,0.00,5108,ME,CI,SO,True,PL2,{'url': 'https://www.northplains.org/library'},2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,True,False,True,True,Fiber,Yes - Major renovation,False,2278.0,4396.0,140.0,Administration; Facilities; Human Resources; I...,Hindi,2020.0,2026.0,NaN,NaN
91,OR0056,2024,Oregon City Public Library,606 John Adams St,Oregon City,97045,606 John Adams St,Oregon City,97045,Clackamas,503-657-8269 x1023,LINCC,1,0,0,18858.0,3498.0,7.0,7.0,12.25,30,295,True,True,11,0,5,20,290000.0,0.0,2854786.0,9895,0,4522.0,236277.0,54778.0,0.0,0.0,0.0,1173749.0,715917.0,120779.0,56765.0,37507.0,927800.0,44484.0,9382.0,0.0,55610,8704,3550,289,8205,1010,1290,385,62617,7261,146564,4941,40311,4260,28641,23367,0,0,33325,1381,2231,14430,7,0,22,0,601,32074,111819.0,66541.0,13758.0,10470.0,140638.0,82176.0,352.0,7.0,0.0,0.0,44627.0,53999,139117,249,155992,410,139366.0,Actual count (we track each transaction as it ...,507.0,True,168,4125,94.0,2372.0,74.0,1753.0,17.0,388.0,188.0,2439.0,36.0,4116,12,115,0,0,33.0,9717.0,8592.0,Actual count (we track each transaction as it ...,19,Wi-Fi extends outside building (left on throug...,Actual count (we track each transaction as it ...,"1,000.00",1000.0,LINCC,Sirsi/Dynix,35.0,10.0,12.0,1.0,52,2895.0,156416.0,Actual count (we track each visit as it happens),21000,21000,2016.0,TRUE,TRUE,TRUE,$0.00,55.90,69.80,30.51,42.05,26.95,37.16,22.17,34.52,20.53,28.32,60742,ME,CI,SO,True,PL2,{'url': 'https://www.orcity.org/library'},2023-07-01T00:00:00.000,2024-06-30T00:00:00.000,False,True,False,False,Fiber,No,True,1075.0,8641.0,95.0,Administration; Facilities; Human Resources; I...,Arabic; Chinese (including Mandarin & Cantones...,NaN,NaN,6000000.0,2034.0

#### Quiz
How can we select the `phone` column from this selection?

In [47]:
libraries[phone_lengths > 12]["phone"]

85     503-647-5051 x102
91    503-657-8269 x1023
Name: phone, dtype: object

You can see what's going on! These two libraries add an extension.

Say we want to truncate the column to include only the first 12 characters.
We can use another Pandas string function, `.str`, to index into [each string in a Series](https://pandas.pydata.org/docs/user_guide/text.html#indexing-with-str)
using the same syntax as we would with a string.

As a test case, let's use a fake phone number formatted with an extension.

In [55]:
phone_n = "555-555-5155 x1234"
phone_n[0] # First character

'5'

We can select a range of digits using slicing. The `:` indicates a range of selection.

In [58]:
print(phone_n[:3]) # Slices to the area code
print(phone_n[:12]) # Slices to the main phone number
print(phone_n[-5:]) # Slices the last five characters

555
555-555-5155
x1234

Based on this test case, we want to slice the `phone` from the beginning
of each string up to and including the twelth character.

In [59]:
libraries["phone"].str[:12]

0      541-566-3038
1      541-247-6323
2      541-917-7581
3      503-259-0185
4      503-835-8181
           ...
131    503-570-1592
132    541-679-5501
133    503-980-2413
134    541-547-3741
135    541-849-2128
Name: phone, Length: 136, dtype: object

Assign this back to the `libraries` DataFrame.

In [60]:
libraries["phone"] = libraries["phone"].str[:12]

We know that the libraries at the rows named 85 and 91 had phone numbers with extensions.
To confirm that these values are fixed, use `.loc[]`. Remember, we can pass in a list of
row names or column names to [.loc].

In [61]:
libraries.loc[[85,91], "phone"]

85    503-647-5051
91    503-657-8269
Name: phone, dtype: object

The full list of **[Pandas string handling methods](https://pandas.pydata.org/docs/reference/series.html#string-handling)** is available on the official documentation.